# Generated by Django 3.2 on 2021-04-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210430_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='when',
        ),
        migrations.AddField(
            model_name='blog',
            name='favoritenumber',
            field=models.IntegerField(default='012345', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='email',
            field=models.EmailField(default='~@naver.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.FileField(default='Upload your file:)', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='Upload your image:)', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.URLField(default='instagram.com/~', null=True),
        ),
    ]
